version: "3"
services:
  front:
    image: node:15.6.0-alpine3.10
    working_dir: "/app"
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn dev"